name: Auto Increment Version
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Get current version of .csproj.
        id: get_version
        run: |
          set -e
          VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' StepinFlow/StepinFlow.csproj || echo "1.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment build version.
        id: increment_version
        run: |
          IFS='.' read -r -a VERSION_ARRAY <<< "$VERSION"
          PATCH=$((VERSION_ARRAY[2] + 1))
          NEW_VERSION="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update .csproj version
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ env.NEW_VERSION }}<\/Version>/" StepinFlow/StepinFlow.csproj
          sed -i "s/<FileVersion>.*<\/FileVersion>/<FileVersion>${{ env.NEW_VERSION }}<\/FileVersion>/" StepinFlow/StepinFlow.csproj
          sed -i "s/<InformationalVersion>.*<\/InformationalVersion>/<InformationalVersion>${{ env.NEW_VERSION }}+${{ github.sha }}<\/InformationalVersion>/" StepinFlow/StepinFlow.csproj

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add StepinFlow/StepinFlow.csproj
          git commit -m "Auto-increment version to ${{ env.NEW_VERSION }}" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alekoundas/StepinFlow.git HEAD:${{ github.ref }}
